services:

  frontend:
    build:
      context: ./flight-frontend   
    container_name: flight-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./flight-frontend:/app
      - /app/node_modules
    command: npm run start -- --host 0.0.0.0
